### ISSUE TITLE
folder-scoped approle is not utilized when retrieving folder-scoped credentials

### ISSUE THREAD

**Issue by aajimal** [jenkinsci/hashicorp-vault-plugin#124]
Observed:
When a folder is configured to use a specific approle (different from the globally configured approle) the credentials which are also scoped to the folder (_used for SCM checkout_) are retrieved through the global approle instead of the one which the folder is configured to use. 

To reproduce:
1. Create a new folder in jenkins with approle credential inside this folder along with vault credentials (e.g. vault string credential)
2. Configure folder property to use this new approle (and **not** the global approle)
3. Create new pipeline (with bitbucket/github scm) which uses vault credentials + approle from this folder
4. Observe error  (such as: `FAILED to retrieve username key:
java.lang.RuntimeException: com.datapipe.jenkins.vault.exception.VaultPluginException: Key folder_specific_key could not be found in path secret/folder/credentials`

This seems to prevent the ability to use per-folder approle / credentials for pipeline checkouts.

**Comment by aajimal** [comment]
Could this be related to the fix added in #122 @jetersen? In the there VaultHelper seems to reference explicitly only to the GlobalVaultConfiguration only and not to a more localized scope.

Or perhaps this is not the intent of folder-scoped approles?

**Comment by aajimal** [comment]
Also, I notice that when using `withVault{}` while a pipeline is executing the correct AppRole is chosen.
So this seems like it limited to the pipeline itself when you configure it such as the SCM source.

**Comment by zubcevic** [comment]
I have this issue as well. I want to use a Jenkins controller with only a global vault id for retrieving elements that are allowed to be accessed by anyone. For instance the retrieval of Jenkins Templating Engine libraries. But all folder or job specific configuration will have its own authorised access groups. So I would like to use the vault id (approle) for retrieving the job specific secrets. Especially necessary for centrally managed Jenkins controllers. But the documentation suggests that the expected behaviour is that the vault url and id of the job scope should overrule the global scope when retrieving job specific secrets.

**Comment by aajimal** [comment]
@zubcevic  Right. It seems that the plugin would need to implement `CredentialProvider` which is logged as issue 110 ([here](https://github.com/jenkinsci/hashicorp-vault-plugin/issues/110)) in order to provide this.

One alternative might be to have multiple jenkins masters/controllers and then move folders to be at the root per each master instance. Seems a little bit too cumbersome that way but that could work.

The underlying problem seems to be that the folder/job level vault creds can only be retrieved **inside** of a pipeline execution instead of being used as part of its configuration. So you just can't use folder/job creds to pull the Jenkinsfile itself but you can use folder/job creds while the Jenkinsfile is executing.

**Comment by zubcevic** [comment]
I agree we need the same kind of solution as for aws and azure secrets. 
For migration purposes I would just like to be able to replace all secrets by vault secret references and just add a vault configuration per folder. So all jobs and pipeline jobs could still run without any changes.

**Comment by jetersen** [comment]
The problem is we have two ways of accessing vault secrets during a build, one is folder aware the other is not.

[`VaultHelper`](https://github.com/jenkinsci/hashicorp-vault-plugin/blob/master/src/main/java/com/datapipe/jenkins/vault/credentials/common/VaultHelper.java) is **NOT** folder aware
While [`VaultBuildWrapper`](https://github.com/jenkinsci/hashicorp-vault-plugin/blob/master/src/main/java/com/datapipe/jenkins/vault/VaultBuildWrapper.java) is folder aware.

**Comment by hchakrouun** [comment]
Hi guys,
I worked on this issue lately and I fixed all those unexpected behaviours, I would like to know how can I get a token to push my modifications to this repository, so one of you guys can review my pull request.

Thanks,

**Comment by jetersen** [comment]
@hchakrouun You don't need permission to this repo.

You will fork the repo and submit a pull request.

https://docs.github.com/en/get-started/quickstart/contributing-to-projects

**Comment by hchakrouun** [comment]
Thank  you @jetersen
The pull request was created https://github.com/jenkinsci/hashicorp-vault-plugin/pull/195
