### ISSUE TITLE
FolderVaultConfiguration not working

### ISSUE THREAD

**Issue by yannmontp** [jenkinsci/hashicorp-vault-plugin#134]
Yep 

I have a problem configuring the plugin. I don't want a global configuration. In each project (cloudbees-folder) I would like to configure a credential (appRole) to access the Vault.
  It doesn't seem to work

Different tests:
global configuration without url and credential (appRole)
Global configuration with url without credential (appRole)
Global configuration with url and identifier without rights

![Capture d’écran 2020-10-09 à 13 04 04](https://user-images.githubusercontent.com/10517346/95575985-f9770680-0a2f-11eb-8d6f-ce9fa15cb108.png)
I would like to create the credentials for each project so that they can continue to use credential ID (to switch to vault) and / or substitute the old stored locally : no breakingchange in the pipeline which continues to use IDs
In project folder :
![Capture d’écran 2020-10-09 à 13 10 54](https://user-images.githubusercontent.com/10517346/95576768-490a0200-0a31-11eb-8084-614a40e6e79e.png)

Only global configuration with url and credential (admin) works but projects inherit this configuration (which I don't want)
For all the tets, the plugin configuration is done in the project folder with the right url and the right credential
I can't find this behavior when using the plugin in a freestyle job
can you help me ?
Thank you

**Comment by aajimal** [comment]
This seems possibly related to my issue in #124 .
The folder-scoped approle is not getting used when trying to fetch credentials that are tied to the job configuration (default clone credentials, etc.).

The only time it seems to be used is when the job is already running and your code then requests the credential explicitly. Sort of defeats the purpose for using vault in our case since we cannot have properly segregated folders/jobs with tied to their own approles.
