### ISSUE TITLE
Reasoning for changing the versioning schema

### ISSUE THREAD

**Issue by maxdanilov** [jenkinsci/hashicorp-vault-plugin#207]
## Summary

We've noticed `hashicorp-vault-plugin` has changed its versioning schema from the server to something different.
E.g. the release line was: `3.7.0` -> `3.8.0` -> `336.v182c0fbaaeb7`.

What was the reason to do that? In our case, it's a breaking change, since we're using automation (https://github.com/renovatebot/renovate) to create automatic PRs whenever a new version is released, but that is not functioning anymore since the version is not following the semver.

Does this come from changes in the `release-drafter`?

Would it be possible to at least document the reasoning and the version composition logic?
E.g. in `336.v182c0fbaaeb7`, `182c0fbaaeb7` is the git commit, but what is `336`?

Is it safe to use the releases with this new versioning or they are just intended for development?

**Comment by jetersen** [comment]
Simple automatic versioning as part of https://github.com/jenkinsci/jep/blob/master/jep/229/README.adoc

336 is the total amount of commits in the repo.

The release is fine to use, however currently suffering from a bug #201

**Comment by jetersen** [comment]
Btw renovate should support this.
At least from what is seen here: https://github.com/visualon/jenkins-gitea-plugin/pull/17

**Comment by aabouzaid** [comment]
@jetersen that probably depends on the datasource.

The mentioned PR is a BOM coming from [github-releases](https://github.com/renovatebot/renovate/tree/c814a9a/lib/datasource/github-releases) datasource which has its own [mechanism](https://github.com/renovatebot/renovate/blob/c814a9a/lib/datasource/github-releases/digest.ts) to handle the digest version.

**Comment by jetersen** [comment]
the plugin does publish GitHub releases so should be fine :)

**Comment by aabouzaid** [comment]
@jetersen there is a dedicated datasource called [jenkins-plugins](https://github.com/renovatebot/renovate/tree/c814a9a193a525526bdc187a57bb9e59bed0fc56/lib/datasource/jenkins-plugins) which doesn't call Github but [Jenkins plugins endpoint](https://github.com/renovatebot/renovate/blob/c814a9a193a525526bdc187a57bb9e59bed0fc56/lib/datasource/jenkins-plugins/index.ts#L25) (which is the way to go since not all plugins on Github)

And that's the problem at the moment because it like most of the datasources [uses semver by default](https://github.com/renovatebot/renovate/blob/ea28c6a/lib/datasource/index.ts#L213) and with the new versioning schema, it doesn't work anymore.

Actually, as I see now, [semver-coerced](https://github.com/renovatebot/renovate/tree/ea28c6a4a894fce8b9a6e9668c438c85f2a224f0/lib/versioning/semver-coerced) might work with the new versioning format. I will give it a try now to see how it handles the different formats (till now I was able to detect 4 formats from different Jenkins plugins).

**Comment by aabouzaid** [comment]
It will work only with pure digest like used in hashicorp-vault-plugin but not for plugins that mix semver with the digest without updating the actual semver.

e.g. [jackson2-api-plugin](https://github.com/jenkinsci/jackson2-api-plugin/releases) last 2 versions are `2.13.1-240.vfedd8f46cfde` and `2.13.1-242.v1a45bad25ceb` which both with return `2.13.1` with `semver-coerced`.

Anyway, since the main question in this issue was clarified I believe that a Renovate issue now and not related to `hashicorp-vault-plugin`.

**Comment by jetersen** [comment]
FYI: see https://github.com/jenkins-infra/jenkins.io/issues/4783
